### PR TITLE
5.5

### LINKED ISSUE #71: Unreal Engine 5.5 plugin, cannot compile myself
Hi,

we would love to continue using your great plugin - but we cannot compile it for UE 5.5.

There are some errors with the automated test, it claims the ApplicationContextMask is undefined when you are using it, e.g. here:

IMPLEMENT_SIMPLE_AUTOMATION_TEST(ODGrowBuffer_Tests, "ObjectDeliverer.GrowBuffer.Test", EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::SmokeFilter)

That's the error we get:

C:\jetsim-ue55\Plugins\ObjectDeliverer\Source\ObjectDeliverer\Private\Tests\ODGrowBufferTest.cpp(6): error C2838: 'ApplicationContextMask': illegal qualified name in member declaration

But it seems to be defined in AutomationTest.h, via the GetTestFlagsMap.

This is goes way deeper into Unreal Engine C++ than I'm able to understand. 

It would be awesome if you would be able to release a new version.

Best
Andreas

### PR DESCRIPTION
**Pull request by lehuan5062**
Can compile in 5.5.
This fixes #71.

### CODE REVIEW

**Review by ayumax — COMMENTED** [review]
LGTM. Thanks!
